### ISSUE TITLE
JAR Filename mismatch

### ISSUE THREAD

**Issue by robl0377** [ev3dev-lang-java/template-project-gradle#11]
Seems that the build.gradle produces a **${rootProject.name}-version.jar** 
and deploy.gradle wants to deploy a **${rootProject.name}-version-all.jar**

**Comment by robl0377** [comment]
Yesterday, I used the newest snapshot. I'll try the master..

**Comment by jabrena** [comment]
Hi @robl0377,

Can you upgrade your local project?
https://github.com/ev3dev-lang-java/template-project-gradle/blob/master/gradle/deploy.gradle#L51

It was fixed.

Juan Antonio

**Comment by robl0377** [comment]
Ah found it:
The deploy.gradle has in the task deploy block:
```
                put from: "./build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar", into: "/home/robot/"
```
This should be 
```
            println "scp " + "${projectDir}/build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar " +  remotes.ev3dev.user + "@" + remotes.ev3dev.host + ":/home/robot"
            put from: "${projectDir}/build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar", into: "/home/robot/"
```

**Comment by jabrena** [comment]
Hi Roland, 

I am testing the same project in IntelliJ with multiple bricks.
I will review your notes later.

**Comment by jabrena** [comment]
Hi @robl0377,

The notes that described this morning are the same:

The deploy.gradle has in the task deploy block:
```
                put from: "./build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar", into: "/home/robot/"
```
This should be 
```
            println "scp " + "${projectDir}/build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar " +  remotes.ev3dev.user + "@" + remotes.ev3dev.host + ":/home/robot"
            put from: "${projectDir}/build/libs/" + "${rootProject.name}" + "-" + version + "-all.jar", into: "/home/robot/"
```

The unique differene is the printlln but that statement doesn't have any effect in the ssh execution. I was using the template the whole day. It is very weird.

Please for future issues, use the main project:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues
